### ISSUE TITLE
PHP version requirement

### ISSUE THREAD

**Issue by danki** [nunomaduro/laravel-console-menu#10]
Hehe, readme says "works with 7.0+"
```
  Problem 1
    - This package requires php 7.1.0 but your PHP version (7.1.12) does not satisfy that requirement.
```

**Comment by danki** [comment]
Running following, will do for now
```composer require nunomaduro/laravel-console-menu --ignore-platform-reqs ```

**Comment by nunomaduro** [comment]
@danki I may have fixed that on the latest version. Please re-try. If you have any problems please provide me the full output.

**Comment by nunomaduro** [comment]
@danki Any news on this?

**Comment by mikeerickson** [comment]
Beware, future version of `cli-menu` has a PR plan for PHP 7.2 as minimum version.  We may be stuck in compatibility mode unless this PR gets rejected

https://github.com/php-school/cli-menu/pull/78/commits/8294946bab0ad661be6506d4f98e7dff68f9bb52

**Comment by nunomaduro** [comment]
Hey @mikeerickson.

If they do that, they must release a major version. So that is not a problem. Do you mind of closing this issue?

**Comment by mikeerickson** [comment]
Close away :)
