### ISSUE TITLE
Default background and and white foreground, bad hightlight color

### ISSUE THREAD

**Issue by mikeerickson** [nunomaduro/laravel-console-menu#11]
When using `defaultBackgroundColor` (uses the color of terminal) and a white foreground, the highlight text color is white (should be either default or something other than white.  I am looking for something like `highlightColor`

```
        $option = $this->menu('Select :', ['item 1,item 2'])
            ->setBackgroundColour('default')
            ->setForegroundColour('white')
            ->setExitButtonText('None')
            ->setWidth(60)
            ->open();
```

produces

![image](https://user-images.githubusercontent.com/183153/36924312-f77cd900-1e22-11e8-8f34-b3e453bad27a.png)

**Comment by nunomaduro** [comment]
Hey @mikeerickson! You create an issue on the php-school repository. Since this package is just an wrapper I can't resolve your problem. Sorry.

**Comment by mikeerickson** [comment]
@nunomaduro ya, I realized that after I posted this (meant to come back and close this puppy).  I have patched the issue in `cli-menu`
