### ISSUE TITLE
Warning: The latest version of `cli-menu` has plans from minimum PHP at 7.2

### ISSUE THREAD

**Issue by mikeerickson** [nunomaduro/laravel-console-menu#12]
Hey, beware that the latest version of cli-menu has a PR to make the minimum version of PHP set to 7.2

https://github.com/php-school/cli-menu/pull/78/commits/8294946bab0ad661be6506d4f98e7dff68f9bb52

**Comment by nunomaduro** [comment]
@mikeerickson If they do that: they must release a major release. So no worries! Thanks for the warning tho.

**Comment by mikeerickson** [comment]
I have spoken with him and the PR for 7.2 was an accident, he is rolling it back to 7.1 🤓
