### ISSUE TITLE
[2.0] cli-menu 3.0 integration

### ISSUE THREAD

**Issue by mfour-merickson** [nunomaduro/laravel-console-menu#13]
Hey Bud

I am sure you have seen this already, but `cli-menu` has hit 3.0 (see link below for details) with lots of new features. Curious what your future plans are for integrating this into `laravel-console-menu` 

https://github.com/php-school/cli-menu/releases/tag/3.0.0

**Comment by nunomaduro** [comment]
@mfour-merickson Great news! I should make a major version for this too.

**Comment by mfour-merickson** [comment]
yes you should :-)

**Comment by simonschaufi** [comment]
You just need to adjust this namespace, the rest still works: https://github.com/nunomaduro/laravel-console-menu/blob/master/src/Menu.php#L17

Oh and it would be great if you could also still support Laravel 5.5. I don't have PHP 7.2 yet...

**Comment by nunomaduro** [comment]
@simonschaufi Thanks. I am doing that next week.

**Comment by bastian-schur** [comment]
@nunomaduro Are there any news for cli-menu 3.0 integration release and support laravel 5.5?

**Comment by nunomaduro** [comment]
Hey @mfour-merickson @simonschaufi @bastian-schur @fridzema.

We are working on the PR #15 in order to add support to Cli Menu and Laravel 5.7.

I will not add support to Laravel 5.5. Sorry guys.

**Comment by simonschaufi** [comment]
In the meantime I switched to PHP 7.2 so I'm fine with that. ;) Thank you very much!

**Comment by nunomaduro** [comment]
The version 2.0 has been released. Enjoy!
