### ISSUE TITLE
Strange display error

### ISSUE THREAD

**Issue by ben182** [nunomaduro/laravel-console-menu#16]
Hi,

after upgrading to 2.0, I have some strange displaying bug: 
![image](https://user-images.githubusercontent.com/17678582/45229588-8934ae80-b2c6-11e8-83c2-05e04d5f59df.png)

I use the following code:
`$option = $this->menu('Install ' . $sTitle . '?', [
     'yes',
     'no',
])->disableDefaultItems()->open();`

**Comment by nunomaduro** [comment]
This repository is just a wrapper on top of cli-menu. You should create an issue on the following repository: [https://github.com/php-school/cli-menu](https://github.com/php-school/cli-menu).

Thanks! 👍
