### ISSUE TITLE
Include w/ Laravel Zero by default?

### ISSUE THREAD

**Issue by mikeerickson** [nunomaduro/laravel-console-menu#2]
Nice package, curious if you are going to include out of box w/ Laravel Zero, or leave it up to users to include (I know I will include everytime)

**Comment by nunomaduro** [comment]
@mikeerickson This will be included on Laravel Zero 5.6 by default 👍

**Comment by mikeerickson** [comment]
@nunomaduro Seems this package is not auto loaded with Laravel Zero?  Which (and where) should Service Provided be loaded?

```
  Exception trace:

  1   Illuminate\Console\Command::__call("menu")
      /Users/merickson/docker/localenv/m4-tools/app/Commands/DockerMenuCommand.php : 42

  2   App\Commands\DockerMenuCommand::handle()
      /Users/merickson/docker/localenv/m4-tools/vendor/illuminate/container/BoundMethod.php : 29

  Please use the argument -v to see more details.
```

**Comment by mikeerickson** [comment]
FWIW, did not have this same issue when using `Laravel Console Task`

**Comment by mikeerickson** [comment]
I have added the service provided to `config/app.php` providers array and it is working now, but thinking it should have autoloaded?

**Comment by nunomaduro** [comment]
@mikeerickson For now you must add it on the service provider into app.php. Maybe on the 5.6 we will support auto discovery.

**Comment by mikeerickson** [comment]
OK, well that is what I did.  I was assuming it was auto discovery as there was no mention of adding the Service Provider (easy enough to add myself, could have avoided all of this stuff if it were mentioned :)
