### ISSUE TITLE
Testing Menus

### ISSUE THREAD

**Issue by tonysm** [nunomaduro/laravel-console-menu#29]
Hey, I was wondering if anyone has hinted at testing these menus. I tried calling the command that shows the menu with `$this->artisan()`, but the menu shows up in the console and blocks.

I was thinking if we could add an API to it like

```php
$this->artisan('command')
  ->expectMenu(
    fn (TestMenu $menu) => $menu->hasOption('something')->select('something')
  );
```

(not sure if any of this is possible yet, just thinking of how I'd like to test it if it was possible)

**Comment by nunomaduro** [comment]
We don't have that feature. But feel free to make a pull request.
