### ISSUE TITLE
Call to Undefined Method

### ISSUE THREAD

**Issue by secondmanveran** [nunomaduro/laravel-console-menu#31]
Hey Nuno 

When working with menus in Zero I'm getting this error:

> Call to undefined method NunoMaduro\LaravelConsoleMenu\Menu::setUnselectedMarker()

I don't need it, I was just testing out different settings via the Zero docs for menus. But I thought you should know.

**Comment by secondmanveran** [comment]
Jumped the gun,

> setSelectedMarker

is also missing.

**Comment by owenvoke** [comment]
@secondmanveran, these haven't been available for quite a while (Feb 2020) as they were removed in v3.x of this package (see https://github.com/nunomaduro/laravel-console-menu/pull/24#issuecomment-591117020) which upgraded to [v4.x of `php-school/cli-menu`](https://github.com/php-school/cli-menu/blob/master/UPGRADE.md#400). 👍🏻 

Looks like I removed them from the docs for the package, but they are still on [the LZ docs](https://laravel-zero.com/docs/build-interactive-menus), I'll update this. Thank you. 👍🏻

Edit: That's now updated. 🥳
