### ISSUE TITLE
How to inherit terminal color

### ISSUE THREAD

**Issue by mikeerickson** [nunomaduro/laravel-console-menu#4]
Playing around with project and I see an issue which I am not sure how to handle.  I know I can define the background color, but I am looking for a way to use the terminal background?  I see it is using a default of `light blue` which is tough to read (see screenshot).

![image](https://user-images.githubusercontent.com/183153/35783327-1ce7de24-09ba-11e8-86af-0c59811fc85e.png)

**Comment by nunomaduro** [comment]
@mikeerickson Check if you find something on this readme: https://github.com/php-school/cli-menu.

**Comment by mikeerickson** [comment]
Nope, nothing in there which outlines how this can be done.  

I will see if I can figure out something and PR.  Then you can determine if you want to add to master

**Comment by mikeerickson** [comment]
@nunomaduro FYI, this is what is necessary to provide what i was looking for (supply `default` with `setBackgroundColour` command)

NOTE:  If you dont supply the `setBackgroundColour`, it uses what is displayed in above screenshot 

```
$options = ['Item1','Item2'];
$option = $this->menu('Select Command:', $options)
    ->setForegroundColour('green')
    ->setBackgroundColour('default')
```

**Comment by nunomaduro** [comment]
@mikeerickson Nice! Thanks for the info! 👍
