### ISSUE TITLE
Add `separator` line support in options

### ISSUE THREAD

**Issue by mikeerickson** [nunomaduro/laravel-console-menu#7]
Give something like, display the hyphen as a `separator` 

```
$options = ['Item1','Item2','-','Item3'];
```

Currently, the only way to accomplish this is to use something like `str_repeat('-',80)`

However, this breaks if you have set the width using `setWidth` (see related issue)

**Comment by nunomaduro** [comment]
@mikeerickson Please try on the following way:

```php

$this->menu('Title')
         ->addOptions($optionsA)
         ->addLineBreak('-')
         ->addOptions($optionsB)
         ->open();

```

**Comment by nunomaduro** [comment]
@mikeerickson Please check if my solution also fixes https://github.com/nunomaduro/laravel-console-menu/issues/8.

**Comment by nunomaduro** [comment]
@mikeerickson This is still an issue?

**Comment by mikeerickson** [comment]
Never got around to implementing, had to rebuild tool using node :(

**Comment by nunomaduro** [comment]
I am sorry to ear that.😕

I gonna close this. Fell free to create an issue if you have more questions!
