### ISSUE TITLE
NOTE:  I have cross reported issues to `cli-menu` project

### ISSUE THREAD

**Issue by mikeerickson** [nunomaduro/laravel-console-menu#9]
@nunomaduro 

Just an FYI, my last two reports are probably a better fit for the https://github.com/php-school/cli-menu project, thus I have cross reported them there. Further I have extended an offer to create PRs for them

https://github.com/php-school/cli-menu/issues/70
https://github.com/php-school/cli-menu/issues/71

**Comment by nunomaduro** [comment]
Thanks, @mikeerickson. But I will close this issue due to the lack of activity.
